using Core.Domain;
using Core.Response;
using Dapper;
using Infrastructure.Base;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using System.Data;

namespace Infrastructure
{
    public class AppointmentRepository : BaseRepository, IRepository<Appointment>
    {
        public AppointmentRepository(DBContext dbContext) : base(dbContext) { }


        #region AutoGenerated

        public async Task<Appointment?> SelectOne(int id) =>
            await dbContext.Appointments.Where(appointment => appointment.Id == id).FirstOrDefaultAsync();

        public async Task Insert(Appointment appointment)
        {
            await dbContext.Appointments.AddAsync(appointment);
            await dbContext.SaveChangesAsync();
        }

        public async Task Update(Appointment appointment)
        {
            dbContext.Appointments.Update(appointment);
            await dbContext.SaveChangesAsync();
        }

        public async Task Delete(Appointment appointment)
        {
            dbContext.Appointments.Remove(appointment);
            await dbContext.SaveChangesAsync();
        }

        public async Task<string> SelectAll(int? id, Guid? companyId)
        {
            DynamicParameters parameter = new();
            parameter.Add("_id", id);
            parameter.Add("_company_id", companyId);

            return await connection.QueryFirstAsync<string>("SELECT appointment_selectall(@_id, @_company_id)", parameter);
        }

        #endregion AutoGenerated

        /// <summary>
        /// Checks if the given time slot overlaps with an existing appointment for the same company.
        /// excludeId is used during Update to ignore the current record itself.
        /// </summary>
        public async Task<bool> HasOverlap(Guid companyId, DateTime startTime, DateTime endTime, int? excludeId)
        {
            return await dbContext.Appointments
                .Where(a => a.Company_id == companyId)
                .Where(a => !excludeId.HasValue || a.Id != excludeId.Value)
                .Where(a => startTime < a.EndTime && endTime > a.StartTime)
                .AnyAsync();
        }
    }
}