using Core.Domain;
using Core.Response;
using Dapper;
using Infrastructure.Base;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using System.Data;

namespace Infrastructure
{
    public class BlogRepository : BaseRepository, IRepository<Blog>
    {
        public BlogRepository(DBContext dbContext) : base(dbContext) { }


        #region AutoGenerated

        public async Task<Blog?> SelectOne(int id) =>
            await dbContext.Blogs.Where(blog => blog.Id == id).FirstOrDefaultAsync();

        public async Task Insert(Blog blog)
        {
            await dbContext.Blogs.AddAsync(blog);
            await dbContext.SaveChangesAsync();
        }

        public async Task Update(Blog blog)
        {
            dbContext.Blogs.Update(blog);
            await dbContext.SaveChangesAsync();
        }

        public async Task Delete(Blog blog)
        {
            dbContext.Blogs.Remove(blog);
            await dbContext.SaveChangesAsync();
        }

        public async Task<string> SelectAll(int? id, Guid? companyId)
        {
            DynamicParameters parameter = new();
            parameter.Add("_id", id);
            parameter.Add("_company_id", companyId);

            return await connection.QueryFirstAsync<string>("SELECT blog_selectall(@_id, @_company_id)", parameter);
        }

        #endregion AutoGenerated
    }
}