using Core.Domain;
using Core.Response;
using Dapper;
using Infrastructure.Base;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using System.Data;

namespace Infrastructure
{
    public class BlogCategoryRepository : BaseRepository, IRepository<BlogCategory>
    {
        public BlogCategoryRepository(DBContext dbContext) : base(dbContext) { }


        #region AutoGenerated

        public async Task<BlogCategory?> SelectOne(int id) =>
            await dbContext.BlogCategories.Where(blogCategory => blogCategory.Id == id).FirstOrDefaultAsync();

        public async Task Insert(BlogCategory blogCategory)
        {
            await dbContext.BlogCategories.AddAsync(blogCategory);
            await dbContext.SaveChangesAsync();
        }

        public async Task Update(BlogCategory blogCategory)
        {
            dbContext.BlogCategories.Update(blogCategory);
            await dbContext.SaveChangesAsync();
        }

        public async Task Delete(BlogCategory blogCategory)
        {
            dbContext.BlogCategories.Remove(blogCategory);
            await dbContext.SaveChangesAsync();
        }

        public async Task<string> SelectAll(int? id)
        {
            DynamicParameters parameter = new();
            parameter.Add("_id", id);

            return await connection.QueryFirstAsync<string>("SELECT blog_category_selectall(@_id)", parameter);
        }

        #endregion AutoGenerated
    }
}