using Core.Domain;
using Core.Response;
using Dapper;
using Infrastructure.Base;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using System.Data;

namespace Infrastructure
{
    public class ContactusEnquiryRepository : BaseRepository, IRepository<ContactusEnquiry>
    {
        public ContactusEnquiryRepository(DBContext dbContext) : base(dbContext) { }


        #region AutoGenerated

        public async Task<ContactusEnquiry?> SelectOne(int id) =>
            await dbContext.ContactusEnquiries.Where(contactusEnquiry => contactusEnquiry.Id == id).FirstOrDefaultAsync();

        public async Task Insert(ContactusEnquiry contactusEnquiry)
        {
            await dbContext.ContactusEnquiries.AddAsync(contactusEnquiry);
            await dbContext.SaveChangesAsync();
        }

        public async Task Update(ContactusEnquiry contactusEnquiry)
        {
            dbContext.ContactusEnquiries.Update(contactusEnquiry);
            await dbContext.SaveChangesAsync();
        }

        public async Task Delete(ContactusEnquiry contactusEnquiry)
        {
            dbContext.ContactusEnquiries.Remove(contactusEnquiry);
            await dbContext.SaveChangesAsync();
        }

        public async Task<string> SelectAll(int? id, Guid? companyId, short? status)
        {
            DynamicParameters parameter = new();
            parameter.Add("_id", id);
            parameter.Add("_company_id", companyId);
            parameter.Add("_status", status);

            return await connection.QueryFirstAsync<string>("SELECT contactus_enquiry_selectall(@_id, @_company_id, @_status)", parameter);
        }

        #endregion AutoGenerated
    }
}