using Core.Domain;
using Core.Response;
using Dapper;
using Infrastructure.Base;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using System.Data;

namespace Infrastructure
{
    public class MediaRepository : BaseRepository, IRepository<Media>
    {
        public MediaRepository(DBContext dbContext) : base(dbContext) { }


        #region AutoGenerated

        public async Task<Media?> SelectOne(int id) =>
            await dbContext.Media.Where(media => media.Id == id).FirstOrDefaultAsync();

        public async Task Insert(Media media)
        {
            await dbContext.Media.AddAsync(media);
            await dbContext.SaveChangesAsync();
        }

        public async Task Update(Media media)
        {
            dbContext.Media.Update(media);
            await dbContext.SaveChangesAsync();
        }

        public async Task Delete(Media media)
        {
            dbContext.Media.Remove(media);
            await dbContext.SaveChangesAsync();
        }

        public async Task<string> SelectAll(int? id, Guid? companyId)
        {
            DynamicParameters parameter = new();
            parameter.Add("_id", id);
            parameter.Add("_company_id", companyId);

            return await connection.QueryFirstAsync<string>("SELECT media_selectall(@_id, @_company_id)", parameter);
        }

        #endregion AutoGenerated
    }
}