using Core.Domain;
using Core.Response;
using Dapper;
using Infrastructure.Base;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using System.Data;

namespace Infrastructure
{
    public class MenuRepository : BaseRepository, IRepository<Menu>
    {
        public MenuRepository(DBContext dbContext) : base(dbContext) { }


        #region AutoGenerated

        public async Task<Menu?> SelectOne(int id) =>
            await dbContext.Menus.Where(menu => menu.Id == id).FirstOrDefaultAsync();

        public async Task Insert(Menu menu)
        {
            await dbContext.Menus.AddAsync(menu);
            await dbContext.SaveChangesAsync();
        }

        public async Task Update(Menu Menu)
        {
            dbContext.Menus.Update(Menu);
            await dbContext.SaveChangesAsync();
        }

        public async Task Delete(Menu menu)
        {
            dbContext.Menus.Remove(menu);
            await dbContext.SaveChangesAsync();
        }

        public async Task<string> SelectAll(int? id, short? menuType)
        {
            DynamicParameters parameter = new();
            parameter.Add("_id", id);
            parameter.Add("_menu_type", menuType);

            return await connection.QueryFirstAsync<string>("SELECT menu_selectall(@_id, @_menu_type)", parameter);
        }

        #endregion AutoGenerated

        public async Task<string> SelectByRole(string role, short menuType, int? parentId)
        {
            DynamicParameters parameter = new();
            parameter.Add("_role", role);
            parameter.Add("_menu_type", menuType);
            parameter.Add("_parent_id", parentId);

            return await connection.QueryFirstAsync<string>("SELECT menu_select_byrole(@_role, @_menu_type, @_parent_id)", parameter);
        }
    }
}