using Core.Domain;
using Infrastructure.Base;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Data;

namespace Infrastructure
{
    public class SettingRepository : BaseRepository, IRepository<Setting>
    {
        public SettingRepository(DBContext dbContext) : base(dbContext) { }


        #region AutoGenerated

        public async Task<Setting> SelectOne(int id) =>
            await dbContext.Settings.Where(setting => setting.Id == id).FirstOrDefaultAsync();

        public async Task Insert(Setting setting)
        {
            await dbContext.Settings.AddAsync(setting);
            await dbContext.SaveChangesAsync();
        }

        public async Task Update(Setting setting)
        {
            dbContext.Settings.Update(setting);
            await dbContext.SaveChangesAsync();
        }

        public async Task Delete(Setting setting)
        {
            dbContext.Settings.Remove(setting);
            await dbContext.SaveChangesAsync();
        }

        public async Task<IEnumerable<Setting>> SelectAll(string? key) =>
            await dbContext.Settings.Where(setting => key == null || setting.Key == key).ToListAsync();

        #endregion AutoGenerated
    }
}