using Core.Domain;
using Dapper;
using Infrastructure.Base;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using System.Data;

namespace Infrastructure
{
    public class MenuRightsRepository : BaseRepository, IRepository<MenuRights>
    {
        public MenuRightsRepository(DBContext dbContext) : base(dbContext) { }


        #region AutoGenerated

        public async Task<MenuRights?> SelectOne(int id) =>
            await dbContext.MenuRights.Where(menu => menu.Id == id).FirstOrDefaultAsync();

        public async Task Insert(MenuRights menu)
        {
            await dbContext.MenuRights.AddAsync(menu);
            await dbContext.SaveChangesAsync();
        }

        public async Task Update(MenuRights Menu)
        {
            dbContext.MenuRights.Update(Menu);
            await dbContext.SaveChangesAsync();
        }

        public async Task Delete(MenuRights menu)
        {
            dbContext.MenuRights.Remove(menu);
            await dbContext.SaveChangesAsync();
        }

        public async Task<string> SelectAll(int? id, string? roleId, int? menuId)
        {
            DynamicParameters parameter = new();
            parameter.Add("_id", id);
            parameter.Add("_role", roleId);
            parameter.Add("_menu_id", menuId);

            return await connection.QueryFirstAsync<string>("SELECT menu_rights_selectall(@_id, @_role, @_menu_id)", parameter);
        }

        #endregion AutoGenerated
    }
}